name: 'first-git-action'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  pr_number: # change this
    required: true
    description: 'input description here'
  GITHUB_TOKEN: # change this
    required: true
    description: 'input description here'
outputs:
  pr_state:
    description: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
